version: "3.8"

services:
  web:
    build: .
    container_name: django_csv_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: csvdb
      POSTGRES_USER: csvuser
      POSTGRES_PASSWORD: csvpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
